export interface ManifestItem {
  id: string;
  name: string;
  type: 'tree' | 'rock' | 'path';
  category: 'Trees' | 'Water & Rivers' | 'Flora & Fungi' | 'Rocks & Timber' | 'Structures' | 'Paths';
  cost: number;
  modelPath: string;
  description: string;
  defaultScale?: number;
}

export const ASSET_MANIFEST: ManifestItem[] = [
  // --- TREES (At least 8 diverse tree models) ---
  {
    id: 'nature_tree_oak',
    name: 'Emerald Oak',
    type: 'tree',
    category: 'Trees',
    cost: 20,
    modelPath: '/models/kenney_nature_kit_tree_oak.glb',
    description: 'A classic lush oak with a broad, vibrant canopy.',
    defaultScale: 1.15,
  },
  {
    id: 'nature_tree_fat',
    name: 'Puffy Forest Elm',
    type: 'tree',
    category: 'Trees',
    cost: 22,
    modelPath: '/models/kenney_nature_kit_tree_fat.glb',
    description: 'A round, fluffy canopy tree matching Reference 1.',
    defaultScale: 1.25,
  },
  {
    id: 'nature_tree_pine',
    name: 'Alpine Pine',
    type: 'tree',
    category: 'Trees',
    cost: 25,
    modelPath: '/models/kenney_nature_kit_tree_pineDefaultA.glb',
    description: 'A stately evergreen conifer, fragrant and resilient.',
    defaultScale: 1.2,
  },
  {
    id: 'nature_tree_detailed',
    name: 'Ancient Elder Oak',
    type: 'tree',
    category: 'Trees',
    cost: 35,
    modelPath: '/models/kenney_nature_kit_tree_detailed.glb',
    description: 'A massive sacred tree with dense foliage and roots.',
    defaultScale: 1.3,
  },
  {
    id: 'nature_tree_small',
    name: 'Young Birch',
    type: 'tree',
    category: 'Trees',
    cost: 15,
    modelPath: '/models/kenney_nature_kit_tree_small.glb',
    description: 'A delicate young tree, bringing softness to your glade.',
    defaultScale: 0.95,
  },
  {
    id: 'nature_tree_fall',
    name: 'Autumn Maple',
    type: 'tree',
    category: 'Trees',
    cost: 25,
    modelPath: '/models/kenney_nature_kit_tree_oak_fall.glb',
    description: 'Golden-orange warm foliage that glows in the sunlight.',
    defaultScale: 1.2,
  },
  {
    id: 'nature_tree_palm',
    name: 'Palem Tropis Pesisir',
    type: 'tree',
    category: 'Trees',
    cost: 30,
    modelPath: '/models/tree_palm.glb',
    description: 'Pohon palem tropis dengan pelepah rindang, nuansa pulau tenang.',
    defaultScale: 1.15,
  },
  {
    id: 'mini_forest_tree',
    name: 'Mini Forest Tree',
    type: 'tree',
    category: 'Trees',
    cost: 20,
    modelPath: '/models/kenney_mini_forest_1_0_tree.glb',
    description: 'A stylized miniature evergreen with rich textured bark.',
    defaultScale: 1.1,
  },
  {
    id: 'mini_forest_tree_high',
    name: 'Mini Canopy Tree',
    type: 'tree',
    category: 'Trees',
    cost: 25,
    modelPath: '/models/kenney_mini_forest_1_0_tree-high.glb',
    description: 'A tall canopy tree with natural layered foliage.',
    defaultScale: 1.2,
  },
  {
    id: 'survival_tree',
    name: 'Wilderness Cedar',
    type: 'tree',
    category: 'Trees',
    cost: 22,
    modelPath: '/models/kenney_survival_kit_tree.glb',
    description: 'A rugged forest tree from the survival kit.',
    defaultScale: 1.15,
  },
  {
    id: 'tree_default',
    name: 'Canopy Elm',
    type: 'tree',
    category: 'Trees',
    cost: 20,
    modelPath: '/models/tree_default.glb',
    description: 'A rounded lush elm tree perfect for shade.',
    defaultScale: 1.15,
  },
  {
    id: 'survival_tree_autumn',
    name: 'Amber Ridge Tree',
    type: 'tree',
    category: 'Trees',
    cost: 25,
    modelPath: '/models/kenney_survival_kit_tree-autumn.glb',
    description: 'Rich amber leaves capturing the twilight glow.',
    defaultScale: 1.2,
  },
  {
    id: 'lpset_tree_banana',
    name: 'Pisang Hutan Tropis',
    type: 'tree',
    category: 'Trees',
    cost: 28,
    modelPath: '/models/lpset_tree_banana.glb',
    description: 'Pohon pisang berdaun lebar segar khas tepian rimba Nusantara.',
    defaultScale: 1.15,
  },
  {
    id: 'lpset_tree_coconut',
    name: 'Kelapa Gading Pesisir',
    type: 'tree',
    category: 'Trees',
    cost: 32,
    modelPath: '/models/lpset_tree_coconut.glb',
    description: 'Pohon kelapa menjulang anggun dengan pelepah tropis rindang.',
    defaultScale: 1.2,
  },
  {
    id: 'fabz_tree_savannah',
    name: 'Akasia Sabana Emas',
    type: 'tree',
    category: 'Trees',
    cost: 28,
    modelPath: '/models/fabz_tree_savannah.glb',
    description: 'Pohon akasia bertajuk datar dengan rona hijau-keemasan hangat.',
    defaultScale: 1.18,
  },
  {
    id: 'fabz_tree_baobab',
    name: 'Kanopi Rindang Sabana',
    type: 'tree',
    category: 'Trees',
    cost: 34,
    modelPath: '/models/fabz_tree_baobab.glb',
    description: 'Pohon besar berbatang kokoh dengan tajuk berlapis yang teduh.',
    defaultScale: 1.22,
  },
  {
    id: 'fabz_tree_forest',
    name: 'Jati Rimba Hijau',
    type: 'tree',
    category: 'Trees',
    cost: 22,
    modelPath: '/models/fabz_tree_forest.glb',
    description: 'Pohon hutan tropis berdaun lebat dengan siluet poli rendah yang tegas.',
    defaultScale: 1.15,
  },
  {
    id: 'fabz_pine_green',
    name: 'Cemara Muda Lembah',
    type: 'tree',
    category: 'Trees',
    cost: 18,
    modelPath: '/models/fabz_pine_green.glb',
    description: 'Pohon cemara hijau muda yang ringan dan menyegarkan sudut pulau.',
    defaultScale: 1.1,
  },
  {
    id: 'pack_tree_tiered_pine',
    name: 'Pinus Bertingkat Rimbun',
    type: 'tree',
    category: 'Trees',
    cost: 26,
    modelPath: '/models/pack_tree_tiered_pine.glb',
    description: 'Cemara berlapis tiga gradasi warna daun hijau hutan.',
    defaultScale: 1.2,
  },
  {
    id: 'pack_tree_round_oak',
    name: 'Beringin Kanopi Bulat',
    type: 'tree',
    category: 'Trees',
    cost: 24,
    modelPath: '/models/pack_tree_round_oak.glb',
    description: 'Pohon bertajuk bulat padat dengan perpaduan warna daun alami.',
    defaultScale: 1.15,
  },
  {
    id: 'pack_tree_tall_cypress',
    name: 'Cypress Menara Angin',
    type: 'tree',
    category: 'Trees',
    cost: 28,
    modelPath: '/models/pack_tree_tall_cypress.glb',
    description: 'Pohon menjulang ramping yang memberi aksen vertikal pada diorama.',
    defaultScale: 1.22,
  },
  {
    id: 'lpset_tree_nordic_pine',
    name: 'Cemara Kabut Utara',
    type: 'tree',
    category: 'Trees',
    cost: 26,
    modelPath: '/models/lpset_tree_nordic_pine.glb',
    description: 'Pohon konifer hijau zamrud tua dengan tekstur geometris tajam.',
    defaultScale: 1.18,
  },
  {
    id: 'forest_dead_tree',
    name: 'Pohon Ranting Kering',
    type: 'tree',
    category: 'Trees',
    cost: 16,
    modelPath: '/models/forest_dead_tree.glb',
    description: 'Siluet pohon kayu kering artistik untuk kontras alami di tepi batu.',
    defaultScale: 1.1,
  },

  // --- FLORA & FUNGI ---
  {
    id: 'nature_flower_red',
    name: 'Crimson Wildflowers',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 10,
    modelPath: '/models/kenney_nature_kit_flower_redA.glb',
    description: 'Bright red forest blossoms that attract butterflies.',
    defaultScale: 1.0,
  },
  {
    id: 'nature_flower_yellow',
    name: 'Golden Buttercups',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 10,
    modelPath: '/models/kenney_nature_kit_flower_yellowA.glb',
    description: 'Sunny yellow meadow flowers waving in the breeze.',
    defaultScale: 1.0,
  },
  {
    id: 'nature_flower_purple',
    name: 'Lavender Bluebells',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 10,
    modelPath: '/models/kenney_nature_kit_flower_purpleA.glb',
    description: 'Gentle purple flowers with soothing fragrance.',
    defaultScale: 1.0,
  },
  {
    id: 'nature_mushroom_red',
    name: 'Fairy Cap Shrooms',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 12,
    modelPath: '/models/kenney_nature_kit_mushroom_redGroup.glb',
    description: 'Vibrant red-spotted forest mushrooms.',
    defaultScale: 1.1,
  },
  {
    id: 'nature_bush',
    name: 'Lush Forest Shrub',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 10,
    modelPath: '/models/kenney_nature_kit_plant_bushDetailed.glb',
    description: 'A dense leafy green bush that softens corners.',
    defaultScale: 1.1,
  },
  {
    id: 'shroom_amanita',
    name: 'Jamur Amanita Merah',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 14,
    modelPath: '/models/shroom_amanita.glb',
    description: 'Jamur payung merah berbintik putih ikonik penghias lantai hutan.',
    defaultScale: 1.05,
  },
  {
    id: 'shroom_chanterelle',
    name: 'Jamur Chanterelle Emas',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 14,
    modelPath: '/models/shroom_chanterelle.glb',
    description: 'Jamur hutan kuning keemasan berbentuk corong yang hangat.',
    defaultScale: 1.05,
  },
  {
    id: 'lp_mushroom_cluster',
    name: 'Rumpun Jamur Payung',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 15,
    modelPath: '/models/lp_mushroom_cluster.glb',
    description: 'Keluarga jamur hutan yang tumbuh berdampingan di tanah lembap.',
    defaultScale: 1.08,
  },
  {
    id: 'forest_fruit_bush',
    name: 'Semak Beri Merah',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 14,
    modelPath: '/models/forest_fruit_bush.glb',
    description: 'Semak hijau rimbun penuh buah beri merah kesukaan burung rimba.',
    defaultScale: 1.1,
  },
  {
    id: 'fabz_flower_crimson',
    name: 'Bunga Mekar Delima',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 12,
    modelPath: '/models/fabz_flower_crimson.glb',
    description: 'Bunga merah bermahkota kuning cerah yang mengundang lebah madu.',
    defaultScale: 1.05,
  },
  {
    id: 'fabz_plant_fern',
    name: 'Pakis Hutan Tropis',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 10,
    modelPath: '/models/fabz_plant_fern.glb',
    description: 'Tanaman pakis berdaun menjari untuk memperkaya dasar pepohonan.',
    defaultScale: 1.05,
  },
  {
    id: 'lp_bush_round',
    name: 'Semak Belukar Rapi',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 11,
    modelPath: '/models/lp_bush_round.glb',
    description: 'Semak bulat hijau segar dengan potongan geometris yang menenangkan.',
    defaultScale: 1.05,
  },

  // --- ROCKS & TIMBER ---
  {
    id: 'nature_rock_tall',
    name: 'Mountain Crag',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 20,
    modelPath: '/models/kenney_nature_kit_rock_tallA.glb',
    description: 'A tall rocky pillar that adds vertical depth.',
    defaultScale: 1.3,
  },
  {
    id: 'nature_rock_small',
    name: 'Pebble Cluster',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 10,
    modelPath: '/models/kenney_nature_kit_rock_smallA.glb',
    description: 'A calm cluster of rounded pebbles along the bank.',
    defaultScale: 0.9,
  },
  {
    id: 'nature_stump',
    name: 'Weathered Tree Stump',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 12,
    modelPath: '/models/kenney_nature_kit_stump_roundDetailed.glb',
    description: 'An ancient weathered stump carpeted with soft moss.',
    defaultScale: 1.0,
  },
  {
    id: 'survival_log',
    name: 'Fallen Hollow Log',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 14,
    modelPath: '/models/kenney_survival_kit_tree-log.glb',
    description: 'A rustic fallen timber offering shelter for wildlife.',
    defaultScale: 1.1,
  },
  {
    id: 'survival_rock_flat_grass',
    name: 'Batu Pipih Berumput',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 14,
    modelPath: '/models/kenney_survival_kit_rock-flat-grass.glb',
    description: 'Batu kali pipih berteras rumput yang tenang di tepi pulau.',
    defaultScale: 1.15,
  },
  {
    id: 'survival_tree_log_small',
    name: 'Batang Kayu Rebah Alami',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 12,
    modelPath: '/models/kenney_survival_kit_tree-log-small.glb',
    description: 'Kayu glondongan kecil alami tempat peristirahatan satwa.',
    defaultScale: 1.1,
  },
  {
    id: 'survival_tree_autumn_tall',
    name: 'Pohon Keemasan Tinggi',
    type: 'tree',
    category: 'Trees',
    cost: 22,
    modelPath: '/models/kenney_survival_kit_tree-autumn-tall.glb',
    description: 'Pohon musim gugur menjulang tinggi dengan daun keemasan hangat.',
    defaultScale: 1.25,
  },
  {
    id: 'lpset_rock_mossy_a',
    name: 'Batu Lumut Zamrud',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 16,
    modelPath: '/models/lpset_rock_mossy_a.glb',
    description: 'Batu alam tua yang diselimuti hamparan lumut hijau lembut.',
    defaultScale: 1.1,
  },
  {
    id: 'lpset_rock_mossy_b',
    name: 'Bongkahan Batu Berlumut',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 18,
    modelPath: '/models/lpset_rock_mossy_b.glb',
    description: 'Batu sungai besar berlumut tebal, cocok di tepian aliran air.',
    defaultScale: 1.12,
  },
  {
    id: 'fabz_rounded_rock',
    name: 'Batu Kali Halus',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 12,
    modelPath: '/models/fabz_rounded_rock.glb',
    description: 'Batu bulat abu-abu natural dengan faset poli rendah yang bersih.',
    defaultScale: 1.08,
  },
  {
    id: 'pack_stump_moss',
    name: 'Tunggul Kayu Lingkar',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 12,
    modelPath: '/models/pack_stump_moss.glb',
    description: 'Tunggul pohon tua dengan detail lingkaran tahun yang hangat.',
    defaultScale: 1.05,
  },
  {
    id: 'fabz_cut_trunk',
    name: 'Pangkal Kayu Tebang',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 12,
    modelPath: '/models/fabz_cut_trunk.glb',
    description: 'Potongan pangkal batang kayu berakar kokoh.',
    defaultScale: 1.05,
  },
  {
    id: 'pack_wood_log_moss',
    name: 'Kayu Rebah Hutan Tua',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 16,
    modelPath: '/models/pack_wood_log_moss.glb',
    description: 'Batang pohon tumbang bercabang yang menjadi rumah mikro-ekosistem.',
    defaultScale: 1.1,
  },
  {
    id: 'pack_wood_branch',
    name: 'Ranting Kayu Alami',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 10,
    modelPath: '/models/pack_wood_branch.glb',
    description: 'Cabang kayu kering di atas rumput untuk sentuhan hutan liar.',
    defaultScale: 1.05,
  },
  {
    id: 'lp_ancient_root',
    name: 'Akar Pohon Purba',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 15,
    modelPath: '/models/lp_ancient_root.glb',
    description: 'Jalinan akar kayu menjalar yang menambah tekstur tanah pulau.',
    defaultScale: 1.08,
  },

  // --- COZY SANCTUARY CAMP ---
  {
    id: 'survival_campfire',
    name: 'Api Unggun Suaka',
    type: 'rock',
    category: 'Structures',
    cost: 25,
    modelPath: '/models/kenney_survival_kit_campfire-pit.glb',
    description: 'Lingkaran batu dengan bara api hangat untuk malam perenungan di rimba.',
    defaultScale: 1.1,
  },
  {
    id: 'survival_tent',
    name: 'Tenda Penjaga Rimba',
    type: 'rock',
    category: 'Structures',
    cost: 30,
    modelPath: '/models/kenney_mini_forest_1_0_tent.glb',
    description: 'Tenda kemah kanvas alami tempat berteduh dan beristirahat di bawah naungan kanopi rimba.',
    defaultScale: 0.58,
  },

  // --- WATER & RIVERS ---
  {
    id: 'river_stream',
    name: 'Aliran Sungai Rimba',
    type: 'path',
    category: 'Water & Rivers',
    cost: 10,
    modelPath: '/models/river_stream.glb',
    description: 'Aliran air sungai jernih dengan tepian pasir untuk membelah pulau dan disambungkan jembatan.',
    defaultScale: 1.0,
  },
  {
    id: 'mini_forest_bridge',
    name: 'Jembatan Kayu Rimba',
    type: 'path',
    category: 'Paths',
    cost: 24,
    modelPath: '/models/kenney_mini_forest_1_0_bridge.glb',
    description: 'Jembatan kayu alami khas hutan rimba untuk menghubungkan tepian sungai.',
    defaultScale: 1.08,
  },
  {
    id: 'nature_bridge_wood',
    name: 'Jembatan Lengkung Kayu',
    type: 'path',
    category: 'Paths',
    cost: 25,
    modelPath: '/models/kenney_nature_kit_bridge_wood.glb',
    description: 'Jembatan kayu melengkung yang tenang di atas aliran sungai.',
    defaultScale: 1.1,
  },
  {
    id: 'fabz_flat_bridge',
    name: 'Jembatan Papan Rimba',
    type: 'path',
    category: 'Paths',
    cost: 28,
    modelPath: '/models/fabz_flat_bridge.glb',
    description: 'Jembatan kayu bertiang pancang kokoh untuk menyeberangi aliran sungai.',
    defaultScale: 1.08,
  },
  {
    id: 'nature_path_stepping',
    name: 'Batu Pijakan Alami',
    type: 'path',
    category: 'Paths',
    cost: 8,
    modelPath: '/models/kenney_nature_kit_path_stoneCircle.glb',
    description: 'Susunan batu pijakan bulat alami di sela rerumputan rimba.',
    defaultScale: 1.0,
  },
  {
    id: 'nature_path_wood',
    name: 'Jalur Papan Kayu',
    type: 'path',
    category: 'Paths',
    cost: 8,
    modelPath: '/models/kenney_nature_kit_path_wood.glb',
    description: 'Pijakan bilah kayu alami di sepanjang tepian sungai.',
    defaultScale: 1.0,
  },
  {
    id: 'nature_path_stone',
    name: 'Batu Lempeng Lembah',
    type: 'path',
    category: 'Paths',
    cost: 5,
    modelPath: '/models/kenney_nature_kit_path_stone.glb',
    description: 'Batu lempeng alami untuk jejak langkah di tengah hutan.',
    defaultScale: 1.0,
  },

  // --- KENNEY PLATFORMER KIT NATURE EXPANSION ---
  {
    id: 'platformer_tree',
    name: 'Pohon Bundar Rimba',
    type: 'tree',
    category: 'Trees',
    cost: 18,
    modelPath: '/models/tree.glb',
    description: 'Pohon bundar kartun dengan kanopi hijau lembut dan batang kayu hangat.',
    defaultScale: 1.1,
  },
  {
    id: 'platformer_tree_pine',
    name: 'Pinus Kanopi Runcing',
    type: 'tree',
    category: 'Trees',
    cost: 22,
    modelPath: '/models/tree-pine.glb',
    description: 'Pohon pinus kerucut gagah penyejuk sudut pulau.',
    defaultScale: 1.15,
  },
  {
    id: 'platformer_tree_pine_small',
    name: 'Pinus Muda Lembah',
    type: 'tree',
    category: 'Trees',
    cost: 14,
    modelPath: '/models/tree-pine-small.glb',
    description: 'Bibit pinus muda imut pelengkap rumpun hutan.',
    defaultScale: 1.05,
  },
  {
    id: 'platformer_tree_snow',
    name: 'Pohon Bundar Salju',
    type: 'tree',
    category: 'Trees',
    cost: 28,
    modelPath: '/models/tree-snow.glb',
    description: 'Pohon bundar berselimut salju tebal murni (Terbuka di Level 20).',
    defaultScale: 1.1,
  },
  {
    id: 'platformer_tree_pine_snow',
    name: 'Pinus Salju Abadi',
    type: 'tree',
    category: 'Trees',
    cost: 32,
    modelPath: '/models/tree-pine-snow.glb',
    description: 'Pohon pinus es dengan lapisan salju abadi pegunungan (Terbuka di Level 20).',
    defaultScale: 1.15,
  },
  {
    id: 'platformer_tree_pine_snow_small',
    name: 'Pinus Salju Muda',
    type: 'tree',
    category: 'Trees',
    cost: 20,
    modelPath: '/models/tree-pine-snow-small.glb',
    description: 'Pinus kerdil bersalju untuk taman musim dingin (Terbuka di Level 20).',
    defaultScale: 1.05,
  },
  {
    id: 'platformer_plant',
    name: 'Semak Pakis Rimba',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 8,
    modelPath: '/models/plant.glb',
    description: 'Rumpun tanaman daun hijau segar bertekstur lembut.',
    defaultScale: 1.1,
  },
  {
    id: 'platformer_flowers',
    name: 'Rumpun Bunga Padang',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 10,
    modelPath: '/models/flowers.glb',
    description: 'Kelopak bunga padang rumput ceria penghias tepi jalan.',
    defaultScale: 1.15,
  },
  {
    id: 'platformer_flowers_tall',
    name: 'Bunga Liar Semampai',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 12,
    modelPath: '/models/flowers-tall.glb',
    description: 'Tangkai bunga liar anggun menjulang di sela rumput.',
    defaultScale: 1.1,
  },
  {
    id: 'platformer_mushrooms',
    name: 'Trio Jamur Rimba',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 12,
    modelPath: '/models/mushrooms.glb',
    description: 'Tiga serangkai jamur hutan lucu di bawah naungan pohon.',
    defaultScale: 1.1,
  },
  {
    id: 'platformer_hedge',
    name: 'Pagar Tanaman Asri',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 10,
    modelPath: '/models/hedge.glb',
    description: 'Pagar semak hijau rapi pembatas taman santai.',
    defaultScale: 1.0,
  },
  {
    id: 'platformer_hedge_corner',
    name: 'Sudut Pagar Tanaman',
    type: 'rock',
    category: 'Flora & Fungi',
    cost: 10,
    modelPath: '/models/hedge-corner.glb',
    description: 'Siku belokan pagar semak hijau untuk sudut petak.',
    defaultScale: 1.0,
  },
  {
    id: 'platformer_rocks',
    name: 'Batu Bulat Lembah',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 10,
    modelPath: '/models/rocks.glb',
    description: 'Sepasang batuan bundar halus bergaya kartun bersahaja.',
    defaultScale: 1.1,
  },
  {
    id: 'platformer_stones',
    name: 'Batu Kerikil Pijakan',
    type: 'rock',
    category: 'Rocks & Timber',
    cost: 6,
    modelPath: '/models/stones.glb',
    description: 'Taburan kerikil halus alami untuk tepian jalan atau sungai.',
    defaultScale: 1.05,
  },
];

const LEGACY_VARIANT_REDIRECT: Record<string, string> = {
  tree: 'platformer_tree',
  tree_pine: 'platformer_tree_pine',
  tree_pine_small: 'platformer_tree_pine_small',
  tree_snow: 'platformer_tree_snow',
  tree_pine_snow: 'platformer_tree_pine_snow',
  plant: 'platformer_plant',
  flowers: 'platformer_flowers',
  flowers_tall: 'platformer_flowers_tall',
  mushrooms: 'platformer_mushrooms',
  rock_large: 'fabz_rounded_rock',
  rock_largeA: 'fabz_rounded_rock',
  nature_rock_large: 'fabz_rounded_rock',
  hedge: 'platformer_hedge',
  hedge_corner: 'platformer_hedge_corner',
  rocks: 'platformer_rocks',
  stones: 'platformer_stones',
  bridge_stone: 'mini_forest_bridge',
  nature_bridge_stone: 'mini_forest_bridge',
  windmill: 'nature_tree_detailed',
  watermill: 'nature_tree_detailed',
  fabz_cactus: 'fabz_plant_fern',
  fence: 'pack_wood_log_moss',
  survival_fence: 'pack_wood_log_moss',
  forest_fence_rustic: 'pack_wood_log_moss',
  lantern: 'shroom_chanterelle',
  signpost: 'pack_stump_moss',
  survival_signpost: 'pack_stump_moss',
  fabz_wooden_sign: 'pack_stump_moss',
  tent: 'survival_tent',
  mini_forest_tent: 'survival_tent',
  tent_survival: 'survival_tent',
};

// Helper to look up manifest item by id or model variant
export function getManifestItem(idOrVariant?: string | null): ManifestItem | undefined {
  if (!idOrVariant) return undefined;
  const normalized = LEGACY_VARIANT_REDIRECT[idOrVariant] || idOrVariant;
  return (
    ASSET_MANIFEST.find((item) => item.id === normalized) ||
    ASSET_MANIFEST.find((item) => item.modelPath.includes(normalized))
  );
}

